project:
  type: website

website:
  title: "Global Mental Health Conference"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

