project:
  type: website

website:
  title: "Global Mental Health Conference"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: sessions.qmd
        text: Sessions Overview
      - href: symposia1.qmd
        text: Symposia Round 1
      - href: symposia2.qmd
        text: Symposia Round 2
    right:
      - href: https://globalhealth.duke.edu/center-global-mental-health
        text: Duke Center for Global Mental Health

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

